# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ConnectionStrings.AzureSQL: $(AzureSQL)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/Ocean2Ocean.Tests/bin/Release/netcoreapp3.1/'
    jsonTargetFiles: 'appsettings.json'
    xmlTransformationRules: '' # disabled

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/Ocean2Ocean.Mvc/bin/Release/netcoreapp3.1/'
    jsonTargetFiles: 'appsettings.json'
    xmlTransformationRules: '' # disabled

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/Ocean2Ocean.Mvc/bin/Release/netcoreapp3.1/'
    publishLocation: 'pipeline'